#!/usr/bin/env python

import django

django.setup()


from users.models import User


class Seeder:
    def create_superuser(
        self, username="admin", password="password123", email="mischke@protonmail.com"
    ):
        self.user = User.objects.create_user(
            username=username,
            password=password,
            email=email,
            first_name="Adam",
            last_name="Mischke",
            is_staff=True,
            is_superuser=True,
        )


print("==> initializing postgres database with seed..")
seed = Seeder()
seed.create_superuser()
print("==> done!")
