#!/usr/bin/env python

import django

django.setup()


from users.models import User  # noqa: <Error>


class Seeder:
    def create_superuser(
        self, username="admin", password="password123", email="admin@django.com"
    ):
        self.user = User.objects.create_user(
            username=username,
            password=password,
            email=email,
            first_name="Admin",
            last_name="User",
            is_staff=True,
            is_superuser=True,
        )


print("==> initializing postgres database with seed..")
seed = Seeder()
seed.create_superuser()
print("==> done!")
